AppName: Finders
version: 0.0.0

jwt:
  signing-key: Elyar

system:
  ip: "127.0.0.1"
  port: 8660
  env: "DEBUG"
  DB: mysql

log:
  prefix: "[Finders-Server]"
  logfile: false #此选项会让日志带有文件及行号
  stdout: "DEBUG"
  file: "DEBUG"

mysql:
  username: root
  password: 998120
  addr: 127.0.0.1:3306
  database: finders-test
  # database: finders
  config: charset=utf8&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

sqlite:
  path: finders.db
  log-mode: true
  config: loc=Asia/Shanghai
