AppName: Finders
version: 0.0.0

system:
  ip: "127.0.0.1"
  port: 8080
  env: "DEBUG"
  DB: "mysql"

log:
  prefix: "[Finders-Server]"
  logfile: false #此选项会让日志带有文件及行号
  stdout: "DEBUG"
  file: "DEBUG"
