AppName: Finders
version: 0.0.0

jwt:
  signing-key: Elyar

system:
  ip: "127.0.0.1"
  port: 8660
  env: "DEBUG"
  DB: mysql

log:
  prefix: "[Finders-Server]"
  logfile: false #此选项会让日志带有文件及行号
  stdout: "DEBUG"
  file: "DEBUG"

mysql:
  username: root
  password: 0520SBLI
  addr: 127.0.0.1:3306
  database: finders_test
  # database: finders
  config: charset=utf8&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

sqlite:
  path: finders.db
  log-mode: true
  config: loc=Asia/Shanghai

redis:
  addr: 127.0.0.1:6379
  password:
  maxidle: 30
  maxactive: 30
  idletimeout: 200

appconfig:
  prefixurl: http://127.0.0.1:8660
  runtimerootpath: runtime/
  imagesavepath: upload/images/
  imagemaxsize: 5
  imageallowexts: .jpg,.jpeg,.png
