// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-07-12 11:13:18.888558 +0800 CST m=+0.065205690

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello": {
            "get": {
                "description": "get record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "some_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0 ,\"data\":{} ,\"msg\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/add_denylist": {
            "post": {
                "description": "拉入黑名单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "拉入黑名单"
                ],
                "summary": "拉入黑名单",
                "parameters": [
                    {
                        "description": "需要拉入黑名单的人的ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.FollowForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:\"\", \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/follow": {
            "post": {
                "description": "关注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注"
                ],
                "summary": "关注",
                "parameters": [
                    {
                        "description": "需要关注的人的ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.FollowForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:\"\", \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/get_denylist": {
            "get": {
                "description": "获取本用户的黑名单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取本用户的黑名单列表"
                ],
                "summary": "获取本用户的黑名单列表",
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data: {userId:\"\",avatar:\"url\",nickName:\"\",introduction:\"\"}, \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/get_fans": {
            "get": {
                "description": "获取一个用户的粉丝列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取一个用户的粉丝列表"
                ],
                "summary": "获取一个用户的粉丝列表",
                "parameters": [
                    {
                        "description": "需要获取粉丝列表的人的ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.FollowForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data: {\"code\": 0, data: {userId:\"\",avatar:\"url\",nickName:\"\",introduction:\"\"}, \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/get_follow": {
            "get": {
                "description": "获取一个用户的关注列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取一个用户的关注列表"
                ],
                "summary": "获取一个用户的关注列表",
                "parameters": [
                    {
                        "description": "需要获取关注列表名单的人的ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.FollowForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data: {\"code\": 0, data: {userId:\"\",avatar:\"url\",nickName:\"\",introduction:\"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/login": {
            "post": {
                "description": "登录或注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录或注册"
                ],
                "summary": "登录或注册",
                "parameters": [
                    {
                        "description": "手机号 可选择手机号和验证码登录 或用户名和密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.loginByUserNameOrPhone"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:\"\", \"msg\": \"\", token: \"token\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\", token: \"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/remove_denylist": {
            "post": {
                "description": "将一个人从黑名单中移除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "将一个人从黑名单中移除"
                ],
                "summary": "将一个人从黑名单中移除",
                "parameters": [
                    {
                        "description": "需要取消黑名单的人的ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.FollowForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:\"\", \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/unfollow": {
            "post": {
                "description": "取消关注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "取消关注"
                ],
                "summary": "取消关注",
                "parameters": [
                    {
                        "description": "需要取消关注的人的ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.FollowForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:\"\", \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/update_profile": {
            "post": {
                "description": "更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "更新用户信息"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "任意字段都可更新，可一次更新多个字段",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userService.UpdateForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:\"\", \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/upload_image": {
            "post": {
                "description": "上传图片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "上传图片"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:{image_url:\"\"}, \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/upload_video": {
            "post": {
                "description": "上传视屏",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "上传视屏"
                ],
                "summary": "上传视屏",
                "parameters": [
                    {
                        "type": "file",
                        "description": "视屏",
                        "name": "video",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: {\"code\": 0, data:{video_url:\"\"}, \"msg\": \"\"}; failure: {\"code\": -1, data:\"\", \"msg\": \"error msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "userService.FollowForm": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        },
        "userService.UpdateForm": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "[ 2] address                                        VARCHAR[200]         strue   primary: false  auto: false",
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "birthday": {
                    "description": "[ 6] birthday                                       VARCHAR[20]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "blood_type": {
                    "description": "[ 8] blood_type                                     VARCHAR[8]           strue   primary: false  auto: false",
                    "type": "string"
                },
                "constellation": {
                    "description": "[14] constellation                                  VARCHAR[40]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "credit": {
                    "description": "[17] credit                                         INT                  sfalse  primary: false  auto: false",
                    "type": "integer"
                },
                "eamil": {
                    "description": "[ 9] eamil                                          VARCHAR[60]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "feeling": {
                    "description": "[ 5] feeling                                        VARCHAR[20]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "introduction": {
                    "description": "[ 7] introduction                                   VARCHAR[400]         strue   primary: false  auto: false",
                    "type": "string"
                },
                "nickname": {
                    "description": "[ 3] nickname                                       VARCHAR[30]          null: false  primary: false  auto: false",
                    "type": "string"
                },
                "password": {
                    "description": "[ 2] password                                       VARCHAR[30]          null: false  primary: false  auto: false",
                    "type": "string"
                },
                "profession": {
                    "description": "[12] profession                                     VARCHAR[60]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "qq": {
                    "description": "[10] qq                                             VARCHAR[30]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "school": {
                    "description": "[13] school                                         VARCHAR[30]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "sex": {
                    "description": "[ 3] sex                                            VARCHAR[4]           strue   primary: false  auto: false",
                    "type": "string"
                },
                "sexual": {
                    "description": "[ 4] sexual                                         VARCHAR[8]           strue   primary: false  auto: false",
                    "type": "string"
                },
                "truename": {
                    "description": "[ 1] truename                                       VARCHAR[40]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "user_tag": {
                    "description": "[18] user_tag                                       TEXT[65535]          strue   primary: false  auto: false",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "wechat": {
                    "description": "[11] wechat                                         VARCHAR[30]          strue   primary: false  auto: false",
                    "type": "string"
                }
            }
        },
        "userService.loginByUserNameOrPhone": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
