definitions:
  userService.FollowForm:
    properties:
      userID:
        type: string
    type: object
  userService.UpdateForm:
    properties:
      address:
        description: '[ 2] address                                        VARCHAR[200]         strue   primary: false  auto: false'
        type: string
      age:
        type: integer
      birthday:
        description: '[ 6] birthday                                       VARCHAR[20]          strue   primary: false  auto: false'
        type: string
      blood_type:
        description: '[ 8] blood_type                                     VARCHAR[8]           strue   primary: false  auto: false'
        type: string
      constellation:
        description: '[14] constellation                                  VARCHAR[40]          strue   primary: false  auto: false'
        type: string
      credit:
        description: '[17] credit                                         INT                  sfalse  primary: false  auto: false'
        type: integer
      eamil:
        description: '[ 9] eamil                                          VARCHAR[60]          strue   primary: false  auto: false'
        type: string
      feeling:
        description: '[ 5] feeling                                        VARCHAR[20]          strue   primary: false  auto: false'
        type: string
      introduction:
        description: '[ 7] introduction                                   VARCHAR[400]         strue   primary: false  auto: false'
        type: string
      nickname:
        description: '[ 3] nickname                                       VARCHAR[30]          null: false  primary: false  auto: false'
        type: string
      password:
        description: '[ 2] password                                       VARCHAR[30]          null: false  primary: false  auto: false'
        type: string
      profession:
        description: '[12] profession                                     VARCHAR[60]          strue   primary: false  auto: false'
        type: string
      qq:
        description: '[10] qq                                             VARCHAR[30]          strue   primary: false  auto: false'
        type: string
      school:
        description: '[13] school                                         VARCHAR[30]          strue   primary: false  auto: false'
        type: string
      sex:
        description: '[ 3] sex                                            VARCHAR[4]           strue   primary: false  auto: false'
        type: string
      sexual:
        description: '[ 4] sexual                                         VARCHAR[8]           strue   primary: false  auto: false'
        type: string
      truename:
        description: '[ 1] truename                                       VARCHAR[40]          strue   primary: false  auto: false'
        type: string
      user_tag:
        description: '[18] user_tag                                       TEXT[65535]          strue   primary: false  auto: false'
        type: string
      username:
        type: string
      wechat:
        description: '[11] wechat                                         VARCHAR[30]          strue   primary: false  auto: false'
        type: string
    type: object
  userService.loginByUserNameOrPhone:
    properties:
      code:
        type: string
      password:
        type: string
      phone:
        type: string
      userName:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: get record by ID
      parameters:
      - description: userId
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0 ,"data":{} ,"msg":""}'
          schema:
            type: string
  /v1/user/add_denylist:
    post:
      consumes:
      - application/json
      description: 拉入黑名单
      parameters:
      - description: 需要拉入黑名单的人的ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.FollowForm'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:"", "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 拉入黑名单
      tags:
      - 拉入黑名单
  /v1/user/follow:
    post:
      consumes:
      - application/json
      description: 关注
      parameters:
      - description: 需要关注的人的ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.FollowForm'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:"", "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 关注
      tags:
      - 关注
  /v1/user/get_denylist:
    get:
      consumes:
      - application/json
      description: 获取本用户的黑名单列表
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data: {userId:"",avatar:"url",nickName:"",introduction:""}, "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 获取本用户的黑名单列表
      tags:
      - 获取本用户的黑名单列表
  /v1/user/get_fans:
    get:
      consumes:
      - application/json
      description: 获取一个用户的粉丝列表
      parameters:
      - description: 需要获取粉丝列表的人的ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.FollowForm'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data: {"code": 0, data: {userId:"",avatar:"url",nickName:"",introduction:""}, "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 获取一个用户的粉丝列表
      tags:
      - 获取一个用户的粉丝列表
  /v1/user/get_follow:
    get:
      consumes:
      - application/json
      description: 获取一个用户的关注列表
      parameters:
      - description: 需要获取关注列表名单的人的ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.FollowForm'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data: {"code": 0, data: {userId:"",avatar:"url",nickName:"",introduction:""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 获取一个用户的关注列表
      tags:
      - 获取一个用户的关注列表
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: 登录或注册
      parameters:
      - description: 手机号 可选择手机号和验证码登录 或用户名和密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.loginByUserNameOrPhone'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:"", "msg": "", token: "token"}; failure: {"code": -1, data:"", "msg": "error msg", token: ""}'
          schema:
            type: string
      summary: 登录或注册
      tags:
      - 登录或注册
  /v1/user/remove_denylist:
    post:
      consumes:
      - application/json
      description: 将一个人从黑名单中移除
      parameters:
      - description: 需要取消黑名单的人的ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.FollowForm'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:"", "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 将一个人从黑名单中移除
      tags:
      - 将一个人从黑名单中移除
  /v1/user/unfollow:
    post:
      consumes:
      - application/json
      description: 取消关注
      parameters:
      - description: 需要取消关注的人的ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.FollowForm'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:"", "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 取消关注
      tags:
      - 取消关注
  /v1/user/update_profile:
    post:
      consumes:
      - application/json
      description: 更新用户信息
      parameters:
      - description: 任意字段都可更新，可一次更新多个字段
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userService.UpdateForm'
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:"", "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 更新用户信息
      tags:
      - 更新用户信息
  /v1/user/upload_image:
    post:
      consumes:
      - multipart/form-data
      description: 上传图片
      parameters:
      - description: 图片
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:{image_url:""}, "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 上传图片
      tags:
      - 上传图片
  /v1/user/upload_video:
    post:
      consumes:
      - multipart/form-data
      description: 上传视屏
      parameters:
      - description: 视屏
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 'success: {"code": 0, data:{video_url:""}, "msg": ""}; failure: {"code": -1, data:"", "msg": "error msg"}'
          schema:
            type: string
      summary: 上传视屏
      tags:
      - 上传视屏
swagger: "2.0"
